# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    myresolver:
        class: AppBundle\Service\MyResolver
        tags:
            - { name: overblog_graphql.resolver, alias: myresolver, method: resolveMyResolver }